name: Run tests before changing main.

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      # Client.
      - run: npm --prefix client ci
      - run: npm --prefix client run build
      - run: npm --prefix client test
      # CDK.
      - run: npm --prefix cdk ci
      - run: npm --prefix cdk run test
      - run: npm --prefix cdk run pipeline-synth
